apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-api
  namespace: judge0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0-api
  template:
    metadata:
      labels:
        app: judge0-api
    spec:
      volumes:
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: box
          emptyDir: {}
      containers:
        - name: api
          image: judge0/judge0:latest

          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
          ports:
            - containerPort: 2358
          envFrom:
            - secretRef:
                name: judge0-conn
          env:
            - name: SECRET_KEY_BASE
              value: "1234"
            - name: WEB_CONCURRENCY
              value: "1"
            - name: RAILS_MAX_THREADS
              value: "5"
            - name: PUMA_WORKERS
              value: "1"
            - name: MAX_THREADS
              value: "5"
            - name: RAILS_ENV
              value: "production"
            - name: PORT
              value: "2358"
            - name: JUDGE0_API_VERSION
              value: "1.13.1"
            - name: JUDGE0_VERSION
              value: "0"
            - name: QUEUE
              value: "0"
            - name: REDIS_HOST
              value: "judge0-redis-master"
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
            - name: box
              mountPath: /box
---
apiVersion: v1
kind: Service
metadata:
  name: judge0-api
  namespace: judge0
spec:
  selector:
    app: judge0-api
  ports:
    - port: 2358
      targetPort: 2358
      protocol: TCP
  type: ClusterIP